---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo = TRUE}
    library(timeDate)
    library(lattice)
    data_set <- read.csv("activity.csv",head=TRUE)
    data_set$date <- as.Date(as.character(data_set$date))
```
## What is mean total number of steps taken per day?
```{r}
    options(digits = 2)
    total_data_set <- tapply(data_set$steps,data_set$date,sum,simplify=FALSE,na.rm=TRUE)
    plot(as.numeric(total_data_set),type="h",lwd=7,col="blue",xlab="Steps",main="total number of steps taken each day")
    print("mean total number of steps taken per day:\n")
    tapply(data_set$steps,data_set$date,mean,na.rm=TRUE)
    paste("median total number of steps taken per day:\n")
    tapply(data_set$steps,data_set$date,median,na.rm=TRUE)
```

## What is the average daily activity pattern?
```{r}
    options(digits = 2)
    total_data_set <- tapply(data_set$steps,data_set$interval,mean,simplify=FALSE,na.rm=TRUE)
    plot(as.numeric(total_data_set),type="l",xlab="Interval",ylab="Average of steps per day")
    paste("Which 5-minute interval, on average across all the days in the dataset, not contains the maximum number of steps,the maxinum number of steps is ",as.character(max(data_set$steps,na.rm=TRUE)))
```

## Imputing missing values
```{r}
    paste("the total number of missing values in the dataset ",as.character(nrow(data_set)-sum(complete.cases(data_set$steps))))
    fill_data_set <- data_set
    fill_data_set[is.na(fill_data_set$steps),"steps"] <- mean(data_set$steps,na.rm=TRUE)
    total_data_set <- tapply(fill_data_set$steps,fill_data_set$date,sum,simplify=FALSE,na.rm=TRUE)
    plot(as.numeric(total_data_set),type="h",lwd=7,col="blue",xlab="Steps",main="total number of steps taken each day[Fill Miss Data]")
    print("mean total number of steps taken per day:\n")
    tapply(fill_data_set$steps,fill_data_set$date,mean,na.rm=TRUE)
    paste("median total number of steps taken per day:\n")
    tapply(fill_data_set$steps,fill_data_set$date,median,na.rm=TRUE)

```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
    data_set[isWeekday(data_set$date),"level"] <- c("weekday")
    data_set[isWeekend(data_set$date),"level"] <- c("weekend")
    ansy_data <- tapply(data_set$steps,data_set[,c("level","interval")],mean,na.rm=TRUE)
    resu_data <- cbind(ansy_data[1,],ansy_data[2,])
    resu_data <-data.frame(t(ansy_data))
    axis_x<-row.names(resu_data)
    steps <- as.vector(cbind(resu_data[,1],resu_data[,2]))
    steps <- as.data.frame(steps)
    steps <-data.frame(cbind(steps,interval=as.numeric(rep(axis_x,2)),group=c(rep("weekday",288),rep("weekend",288))))
    xyplot(steps~interval|group,data=steps,type="l",layout=c(1,2),ylab="Numbers of Steps")
    dev.off()
```